window.SPELLING_OPTION_SETS = {
  rootVowels: ["а", "о", "е", "и", "ы", "я"],
  iY: ["и", "ы"],
  sibilants: ["о", "ё", "е", "у", "ю"],
  prePri: ["е", "и"],
  zS: ["з", "с"],
  hardSoft: ["ъ", "ь"],
  suffixVowels: ["и", "е", "о", "ы"],
  oEAYa: ["о", "е", "а", "я"],
  verbVowels: ["е", "и", "а", "я", "у", "ю"],
  nNn: ["н", "нн"]
};

// Заготовка для будущего первого шага игры: пропуск стоит именно в месте проверяемой орфограммы.
window.SPELLING_TASKS = [
  { ruleId: "root-alternation", word: "пригарь", masked: "приг_рь", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "изгарь", masked: "изг_рь", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "выгарки", masked: "выг_рки", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "утварь", masked: "утв_рь", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "пловец", masked: "пл_вец", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "пловчиха", masked: "пл_вчиха", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "плывун", masked: "пл_вун", answer: "ы", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "Ростов", masked: "Р_стов", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "Ростислав", masked: "Р_стислав", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "ростовщик", masked: "р_стовщик", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "выросток", masked: "выр_сток", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "отрасль", masked: "отр_сль", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "полог", masked: "пол_г", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "слоговой", masked: "сл_говой", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "скачок", masked: "ск_чок", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "скачу", masked: "ск_чу", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "сочетание", masked: "соч_тание", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "сочетать", masked: "соч_тать", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "прокляну", masked: "прокл_ну", answer: "я", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "выжимки", masked: "выж_мки", answer: "и", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "равнина", masked: "р_внина", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "ровесник", masked: "р_весник", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "уровень", masked: "ур_вень", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "поровну", masked: "пор_вну", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "равнение", masked: "р_внение", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "зарянка", masked: "з_рянка", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "заревой", masked: "з_ревой", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "заревать", masked: "з_ревать", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "горный", masked: "г_рный", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "клонированный", masked: "кл_нированный", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "root-alternation", word: "перескочу", masked: "переск_чу", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },

  { ruleId: "after-ts-root", word: "цыган", masked: "ц_ган", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "after-ts-root", word: "цыпочках", masked: "ц_почках", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "after-ts-root", word: "цыкнул", masked: "ц_кнул", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "after-ts-root", word: "цыплёнку", masked: "ц_плёнку", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "after-ts-root", word: "цыц", masked: "ц_ц", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "after-ts-root", word: "сестрицын", masked: "сестриц_н", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "after-ts-root", word: "поклацывать", masked: "поклац_вать", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "after-ts-root", word: "побряцывать", masked: "побряц_вать", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },

  { ruleId: "after-sibilants-root", word: "брошюра", masked: "брош_ра", answer: "ю", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "жюри", masked: "ж_ри", answer: "ю", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "парашют", masked: "параш_т", answer: "ю", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "крыжовник", masked: "крыж_вник", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "трущоба", masked: "трущ_ба", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "шорох", masked: "ш_рох", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "шоры", masked: "ш_ры", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "шорник", masked: "ш_рник", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "шоркать", masked: "ш_ркать", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "чокаться", masked: "ч_каться", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "чопорный", masked: "ч_порный", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "шофёр", masked: "ш_фёр", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "жонглёр", masked: "ж_нглёр", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "капюшон", masked: "капюш_н", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "артишок", masked: "артиш_к", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-root", word: "анчоус", masked: "анч_ус", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },

  { ruleId: "checked-root-vowel", word: "честолюбивый", masked: "ч_столюбивый", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "благословение", masked: "благосл_вение", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "наваждение", masked: "нав_ждение", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "утрамбовать", masked: "утр_мбовать", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "экстремальный", masked: "экстр_мальный", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "недосягаемый", masked: "недос_гаемый", answer: "я", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "пристяжная лошадь", masked: "прист_жная лошадь", answer: "я", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "пристежной воротник", masked: "прист_жной воротник", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "перочинный нож", masked: "пер_чинный нож", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "бечёвка", masked: "беч_вка", answer: "ё", options: ["е", "ё", "о"] },
  { ruleId: "checked-root-vowel", word: "проредить", masked: "прор_дить", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "разрежённый", masked: "разр_жённый", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "разряженное", masked: "разр_женное", answer: "я", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "скрепя сердце", masked: "скр_пя сердце", answer: "е", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "умалять", masked: "ум_лять", answer: "а", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "умолять", masked: "ум_лять", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "укрощать", masked: "укр_щать", answer: "о", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "тиснёный", masked: "т_снёный", answer: "и", options: window.SPELLING_OPTION_SETS.rootVowels },
  { ruleId: "checked-root-vowel", word: "почитатель", masked: "поч_татель", answer: "и", options: window.SPELLING_OPTION_SETS.rootVowels },

  { ruleId: "pre-pri", word: "преодолеть", masked: "пр_одолеть", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "преамбула", masked: "пр_амбула", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "превалировать", masked: "пр_валировать", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "премьера", masked: "пр_мьера", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "пренебрежение", masked: "пр_небрежение", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "презирать", masked: "пр_зирать", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "президент", masked: "пр_зидент", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "прелюдия", masked: "пр_людия", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "прекословить", masked: "пр_кословить", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "пресмыкаться", masked: "пр_смыкаться", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "препятствие", masked: "пр_пятствие", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "престиж", masked: "пр_стиж", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "претензия", masked: "пр_тензия", answer: "е", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "прибаутка", masked: "пр_баутка", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "причина", masked: "пр_чина", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "привередливый", masked: "пр_вередливый", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "привидение", masked: "пр_видение", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "привилегия", masked: "пр_вилегия", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "притязание", masked: "пр_тязание", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "приют", masked: "пр_ют", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "приурочить", masked: "пр_урочить", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "примитивный", masked: "пр_митивный", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "приличный", masked: "пр_личный", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "присяга", masked: "пр_сяга", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "природа", masked: "пр_рода", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },
  { ruleId: "pre-pri", word: "прихотливый", masked: "пр_хотливый", answer: "и", options: window.SPELLING_OPTION_SETS.prePri },

  { ruleId: "prefix-z-s", word: "чересчур", masked: "чере_чур", answer: "с", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "дисгармония", masked: "ди_гармония", answer: "с", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "дисбаланс", masked: "ди_баланс", answer: "с", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "разыскной", masked: "ра_ыскной", answer: "з", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "розыск", masked: "ро_ыск", answer: "з", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "роспись", masked: "ро_пись", answer: "с", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "расписной", masked: "ра_писной", answer: "с", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "розлив", masked: "ро_лив", answer: "з", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "разлив", masked: "ра_лив", answer: "з", options: window.SPELLING_OPTION_SETS.zS },
  { ruleId: "prefix-z-s", word: "нездешний", masked: "не_дешний", answer: "з", options: window.SPELLING_OPTION_SETS.zS },

  { ruleId: "prefix-i-y", word: "взимать", masked: "вз_мать", answer: "и", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "prefix-i-y", word: "трёхигольный", masked: "трёх_гольный", answer: "и", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "prefix-i-y", word: "заиндеветь", masked: "за_ндеветь", answer: "и", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "prefix-i-y", word: "обындеветь", masked: "об_ндеветь", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "prefix-i-y", word: "сызнова", masked: "с_знова", answer: "ы", options: window.SPELLING_OPTION_SETS.iY },
  { ruleId: "prefix-i-y", word: "оргединица", masked: "оргед_ница", answer: "и", options: window.SPELLING_OPTION_SETS.iY },

  { ruleId: "separator-hard-soft", word: "подьячий", masked: "под_ячий", answer: "ь", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "арьергард", masked: "ар_ергард", answer: "ь", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "суперъёлка", masked: "супер_ёлка", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "фельдъегерь", masked: "фельд_егерь", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "адъютант", masked: "ад_ютант", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "конъюнктура", masked: "кон_юнктура", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "инъекция", masked: "ин_екция", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "субъект", masked: "суб_ект", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "объект", masked: "об_ект", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "муравьед", masked: "мурав_ед", answer: "ь", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "копьеметатель", masked: "коп_еметатель", answer: "ь", options: window.SPELLING_OPTION_SETS.hardSoft },
  { ruleId: "separator-hard-soft", word: "двухъярусный", masked: "двух_ярусный", answer: "ъ", options: window.SPELLING_OPTION_SETS.hardSoft },

  { ruleId: "suffix-iv-ev", word: "милостивый", masked: "милост_вый", answer: "и", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iv-ev", word: "юродивый", masked: "юрод_вый", answer: "и", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iv-ev", word: "гуттаперчевый", masked: "гуттаперч_вый", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iv-ev", word: "фланелевый", masked: "фланел_вый", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },

  { ruleId: "adverb-o-e-a-ya", word: "досрочно", masked: "досрочн_", answer: "о", options: window.SPELLING_OPTION_SETS.oEAYa },
  { ruleId: "adverb-o-e-a-ya", word: "досрочный", masked: "досрочн_й", answer: "ы", options: ["о", "е", "а", "ы"] },

  { ruleId: "after-sibilants-suffix", word: "ещё", masked: "ещ_", answer: "ё", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "трущоба", masked: "трущ_ба", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "чащоба", masked: "чащ_ба", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "трещотка", masked: "трещ_тка", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "чечётка", masked: "чеч_тка", answer: "ё", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "мелочовка", masked: "мелоч_вка", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "ножовка", masked: "нож_вка", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "ночёвка", masked: "ноч_вка", answer: "ё", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "корчёвка", masked: "корч_вка", answer: "ё", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "сгущёнка", masked: "сгущ_нка", answer: "ё", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "ожог на коже", masked: "ож_г на коже", answer: "о", options: window.SPELLING_OPTION_SETS.sibilants },
  { ruleId: "after-sibilants-suffix", word: "ожёг руку", masked: "ож_г руку", answer: "ё", options: window.SPELLING_OPTION_SETS.sibilants },

  { ruleId: "suffix-iva-eva-va", word: "затмевать", masked: "затм_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "сомневаться", masked: "сомн_ваться", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "застревать", masked: "застр_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "встревать", masked: "встр_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "продлевать", masked: "продл_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "обуревать", masked: "обур_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "растлевать", masked: "растл_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "намереваться", masked: "нам_реваться", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "разевать", masked: "раз_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "увещевать", masked: "увещ_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "разведывать", masked: "развед_вать", answer: "ы", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "исследовать", masked: "исслед_вать", answer: "о", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "расследовать", masked: "расслед_вать", answer: "о", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "заведовать", masked: "завед_вать", answer: "о", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "потчевать", masked: "потч_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "повелевать", masked: "повел_вать", answer: "е", options: window.SPELLING_OPTION_SETS.suffixVowels },
  { ruleId: "suffix-iva-eva-va", word: "навьючивать", masked: "навьюч_вать", answer: "и", options: window.SPELLING_OPTION_SETS.suffixVowels },

  { ruleId: "suffix-ink-enk", word: "горлинка", masked: "горл_нка", answer: "и", options: ["и", "е"] },

  { ruleId: "verb-endings", word: "бреет", masked: "бре_т", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "стелет", masked: "стел_т", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "гонит", masked: "гон_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "держит", masked: "держ_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "дышит", masked: "дыш_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "обидит", masked: "обид_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "слышит", masked: "слыш_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "видит", masked: "вид_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "ненавидит", masked: "ненавид_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "смотрит", masked: "смотр_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "вертит", masked: "верт_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "зависит", masked: "завис_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "терпит", masked: "терп_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "сеет", masked: "се_т", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "лелеет", masked: "леле_т", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "тает", masked: "та_т", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "веет", masked: "ве_т", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "лает", masked: "ла_т", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "клеит", masked: "кле_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "мерещится", masked: "мерещ_тся", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "обезлюдит", masked: "обезлюд_т", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "verb-endings", word: "обезлюдеет", masked: "обезлюд_ет", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },

  { ruleId: "participle-suffixes", word: "движимый", masked: "движ_мый", answer: "и", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "пышущий", masked: "пыш_щий", answer: "у", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "мелющий", masked: "мел_щий", answer: "ю", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "колеблемый", masked: "колебл_мый", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "ропщущий", masked: "ропщ_щий", answer: "у", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "приемлемый", masked: "приемл_мый", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "незыблемый", masked: "незыбл_мый", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "неотъемлемый", masked: "неотъемл_мый", answer: "е", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "брезжущий", masked: "брезж_щий", answer: "у", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "зиждущийся", masked: "зижд_щийся", answer: "у", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "всеобъемлющий", masked: "всеобъемл_щий", answer: "ю", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "дремлющий", masked: "дремл_щий", answer: "ю", options: window.SPELLING_OPTION_SETS.verbVowels },
  { ruleId: "participle-suffixes", word: "алчущий", masked: "алч_щий", answer: "у", options: window.SPELLING_OPTION_SETS.verbVowels },

  { ruleId: "participle-enn", word: "уравненный", masked: "уравн_нный", answer: "е", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "отгрызенный", masked: "отгрыз_нный", answer: "е", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "принесённый", masked: "принес_нный", answer: "ё", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "испечённый", masked: "испеч_нный", answer: "ё", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "достоин", masked: "досто_н", answer: "и", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "удостоен", masked: "удосто_н", answer: "е", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "построенный", masked: "постро_нный", answer: "е", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "скачанный файл", masked: "скач_нный файл", answer: "а", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "скаченная лошадь", masked: "скач_нная лошадь", answer: "е", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "развешанное бельё", masked: "развеш_нное бельё", answer: "а", options: ["е", "ё", "а", "и"] },
  { ruleId: "participle-enn", word: "навешенная дверь", masked: "навеш_нная дверь", answer: "е", options: ["е", "ё", "а", "и"] },

  { ruleId: "single-n", word: "вороной", masked: "воро_ой", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "конченый", masked: "конче_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "названый брат", masked: "назва_ый брат", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "посаженый отец", masked: "посаж_ый отец", answer: "ен", options: ["ен", "енн"] },
  { ruleId: "single-n", word: "приданое", masked: "прида_ое", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "прощеное воскресенье", masked: "проще_ое воскресенье", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "смышлёный", masked: "смышлё_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "стреляный", masked: "стреля_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "кованый", masked: "кова_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "жёваный", masked: "жёва_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "раненый боец", masked: "ране_ый боец", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n", word: "раненный в бою", masked: "ране_ый в бою", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },

  { ruleId: "double-n-imperfective", word: "медленный", masked: "медле_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "виденный", masked: "виде_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "деланный", masked: "дела_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "чеканный", masked: "чека_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "данный", masked: "да_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "желанный", masked: "жела_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "священный", masked: "свяще_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "окаянный", masked: "окая_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "отчаянный", masked: "отчая_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "читанный", masked: "чита_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "слыханный", masked: "слыха_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "негаданный", masked: "негада_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "неслыханный", masked: "неслыха_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-imperfective", word: "невиданный", masked: "невида_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },

  { ruleId: "single-n-an-yan-in", word: "стеклянный", masked: "стекля_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "оловянный", masked: "оловя_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "деревянный", masked: "деревя_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "стремянный", masked: "стремя_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "пряный", masked: "пря_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "юный", masked: "ю_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "румяный", masked: "румя_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "пьяный", masked: "пья_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "single-n-an-yan-in", word: "рьяный", masked: "рья_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },

  { ruleId: "double-n-enn-onn", word: "ветреный", masked: "ветре_ый", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-enn-onn", word: "безветренный", masked: "безветре_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-enn-onn", word: "подветренный", masked: "подветре_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-enn-onn", word: "перочинный", masked: "перочи_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-enn-onn", word: "подлинный", masked: "подли_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "double-n-enn-onn", word: "диковинный", masked: "дикови_ый", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },

  { ruleId: "n-nn-nouns", word: "бесприданница", masked: "бесприда_ица", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "труженик", masked: "труже_ик", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "мученик", masked: "муче_ик", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "пудреница", masked: "пудре_ица", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "мошенник", masked: "моше_ик", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "ставленник", masked: "ставле_ик", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "воспитанник", masked: "воспита_ик", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "бессребреник", masked: "бессребре_ик", answer: "н", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "племянник", masked: "племя_ик", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "утопленник", masked: "утопле_ик", answer: "нн", options: window.SPELLING_OPTION_SETS.nNn },
  { ruleId: "n-nn-nouns", word: "леность", masked: "ле_ость", answer: "н", options: window.SPELLING_OPTION_SETS.nNn }
];
